/**
 * Browser end-to-end tests for the surfaces the design board added:
 * the mark that does the waiting, the quiet skeleton and the price on the
 * face of the wait; the merged typed+spoken mention feed; and the two
 * own-account screens.
 *
 * These are here rather than in vitest for the same reason ui-template.e2e.ts
 * is: the template is one 3,000-line string of DOM-building JavaScript, and
 * the things worth pinning about it — that a handler fires, that a click
 * redraws the right screen, that no page error is thrown — are only true in a
 * real browser. Every test asserts an empty console as well as its own
 * subject, because a thrown TypeError in one of these renderers leaves the
 * previous screen on display and would otherwise pass silently.
 *
 *   npx playwright test tests/e2e/ui-views.e2e.ts
 */
import { type Page } from "@playwright/test";
// `test` comes from guarded-test.ts, not @playwright/test: it aborts every
// request to a real nooticr host before it leaves the browser (#66).
import { test, expect } from "./guarded-test.js";
import { uiTemplateFor } from "../../src/shared/tools.js";

// The substituted view, not the raw template: the raw one still carries its
// __NOOTICR_PLANS__ placeholder, so a test on it would pass with no prices
// and no ledger while the real view was broken.
const NOOTICR_UI_TEMPLATE = uiTemplateFor();

const MENTIONS = {
  term: "nooticr",
  totalMentions: 341,
  byPlatform: { reddit: 61, youtube: 101, tiktok: 191 },
  threads: [
    { post: { platform: "reddit", title: "Anyone else moved their brand-monitoring stack onto an MCP server?", externalUrl: "https://reddit.com/r/x/1", views: 25100 },
      mentionCount: 1, postIsAboutTerm: true,
      mentions: [{ id: "c1", username: "dw_makes", text: "we switched to nooticr last month", likes: 412, replies: 8, postedAt: "2026-09-05T19:25:00Z", hits: 2 }] },
    { post: { platform: "youtube", title: "I tested 6 social listening tools for a week", externalUrl: "https://youtube.com/watch?v=a", views: 96000 },
      mentionCount: 1,
      mentions: [{ id: "c2", username: "aliceb.edits", text: "he says nooticr at 4:12 for anyone skipping", likes: 244, replies: 19, postedAt: "2026-09-05T08:14:00Z" }] },
  ],
  unavailable: [],
};

const SPOKEN = {
  term: "nooticr",
  platforms: ["youtube", "tiktok"],
  candidatesConsidered: 26, transcribed: 14, transcriptsAvailable: 14, matched: 1,
  maxTranscripts: 20, ceilingReached: false,
  hits: [{
    post: { platform: "youtube", title: "I tested 6 social listening tools for a week", externalUrl: "https://youtube.com/watch?v=a", views: 96000, thumbnailUrl: "https://mcp.nooticr.com/media/t.jpg", videoUrl: "https://mcp.nooticr.com/media/x.mp4", contentType: "video", duration: 608, postedAt: "2026-09-04T18:02:00Z" },
    postId: "post:youtube:a", matchCount: 1,
    excerpts: [{ text: "the only one that didn't try to sell me an opinion was nooticr", position: 1200, occurrence: 1, startMs: 252340, timecode: "4:12" }],
    wordCount: 1840, language: "en", autoGenerated: true,
  }],
  unavailable: [],
};

/** A 1x1 transparent GIF, so a poster/thumbnail request resolves to real bytes. */
const PIXEL = Buffer.from(
  "R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7",
  "base64",
);

async function boot(page: Page, tool = "") {
  const errs: string[] = [];
  // Nothing in this file may reach the network.
  //
  // The fixtures below carry real-looking media URLs deliberately — several
  // tests assert on their shape, and a `data:` URI would not exercise the same
  // code path. But every one of these tests then asserts `errs` is empty, so
  // letting the browser actually fetch them made the suite depend on
  // mcp.nooticr.com serving two files: seven render assertions failed with
  // ERR_TUNNEL_CONNECTION_FAILED on any runner without egress, and passed for
  // the wrong reason on one with it. Serving them here keeps the URLs as URLs
  // and the assertion about page errors about page errors.
  await page.route("**/*mcp.nooticr.com/**", (route) => {
    const url = route.request().url();
    if (/\.(mp4|webm|m3u8)$/.test(url)) {
      // An empty 200 rather than a failure: the <video> element raises its own
      // error event for undecodable bytes, which is not a console error, where
      // a 4xx is logged as one and would defeat the point.
      return route.fulfill({ status: 200, contentType: "video/mp4", body: "" });
    }
    return route.fulfill({ status: 200, contentType: "image/gif", body: PIXEL });
  });
  page.on("pageerror", (e) => errs.push(String(e)));
  page.on("console", (m) => { if (m.type() === "error") errs.push(m.text()); });
  // Each tool is served at its own resource URI with its name baked in, which
  // is how the product view tells a create from a patch.
  await page.setContent(tool ? uiTemplateFor(tool) : NOOTICR_UI_TEMPLATE);
  return errs;
}
async function result(page: Page, d: unknown) {
  await page.evaluate((x) => window.postMessage({ method: "ui/notifications/tool-result", params: { structuredContent: x } }, "*"), d);
  await page.waitForTimeout(400);
}

test("loading: inline mark under 6 credits", async ({ page }) => {
  const errs = await boot(page);
  await page.evaluate(() => window.postMessage({ method: "ui/notifications/tool-input", params: { name: "get_social_media", arguments: { url: "https://tiktok.com/x" } } }, "*"));
  await page.waitForTimeout(400);
  await expect(page.locator("svg.mk .iris").first()).toBeVisible();
  expect(await page.locator(".load-price").textContent()).toBe("1 credit");
  expect(await page.locator(".load-centre").count()).toBe(0);
  expect(errs).toEqual([]);
});

test("loading: centred mark over 6 credits", async ({ page }) => {
  const errs = await boot(page);
  await page.evaluate(() => window.postMessage({ method: "ui/notifications/tool-input", params: { name: "search_mentions", arguments: { term: "nooticr" } } }, "*"));
  await page.waitForTimeout(400);
  await expect(page.locator(".load-centre")).toBeVisible();
  expect(await page.locator(".load-sub").textContent()).toContain("21 credits committed");
  expect(await page.locator(".load-what").textContent()).toBe(String.raw`Sweeping 9 networks for "nooticr"`);
  expect(errs).toEqual([]);
});

test("idle mark is the same mark at rest", async ({ page }) => {
  const errs = await boot(page);
  await page.waitForTimeout(300);
  expect(await page.locator("svg.mk").count()).toBe(1);
  expect(await page.locator("svg.mk .iris").count()).toBe(0);
  expect(errs).toEqual([]);
});

test("merged feed: both sweeps, one screen", async ({ page }) => {
  const errs = await boot(page);
  await result(page, MENTIONS);
  await result(page, SPOKEN);
  await page.waitForTimeout(300);
  expect(await page.locator(".mention-total").textContent()).toBe("341 typed · 1 spoken");
  expect(await page.locator("[data-source]").count()).toBe(3);
  expect(await page.locator(".mgroup-about").first().textContent()).toBe("said out loud");
  expect(await page.locator(".mention").count()).toBe(3);
  // Spoken group leads.
  expect(await page.locator(".mgroup").first().getAttribute("data-platform")).toBe("youtube");
  expect(errs).toEqual([]);
});

test("merged feed: source toggle and mixed selection", async ({ page }) => {
  const errs = await boot(page);
  await result(page, MENTIONS);
  await result(page, SPOKEN);
  await page.locator('[data-source="spoken"]').click();
  await page.waitForTimeout(250);
  expect(await page.locator(".mention").count()).toBe(1);
  await page.locator('[data-source="both"]').click();
  await page.waitForTimeout(250);
  // one spoken + one typed
  await page.locator(".mention-pick").nth(0).check();
  await page.locator(".mention-pick").nth(1).check();
  await page.waitForTimeout(250);
  expect(await page.locator("#pickhint").textContent()).toBe("1 spoken, 1 typed");
  expect(errs).toEqual([]);
});

test("spoken-only empty result still draws the funnel", async ({ page }) => {
  const errs = await boot(page);
  await result(page, MENTIONS);
  await result(page, { ...SPOKEN, matched: 0, hits: [] });
  await page.locator('[data-source="spoken"]').click();
  await page.waitForTimeout(250);
  expect(await page.locator(".empty-state .text").textContent()).toBe("Nobody said it out loud");
  // The funnel is the empty state's own sentence, so "nothing was said" and
  // "nothing happened" stay told apart.
  expect(await page.locator(".empty-state").textContent()).toContain("14 transcribed");
  expect(errs).toEqual([]);
});

const CONNECTIONS = {
  connections: [
    { appId: 41, appName: "Studio Frame", influencerId: 7, influencerName: "Studio Frame",
      platform: "tiktok", accountName: "studioframe", status: "active",
      canReadAccount: "yes", canPublishPost: "yes", canManageComments: "no", scopeRecorded: true },
    { appId: 41, appName: "Studio Frame", influencerId: 8, influencerName: "Paper & Pixel",
      platform: "youtube", accountName: "paperandpixel", status: "active",
      canReadAccount: "yes", canPublishPost: "unknown", canManageComments: "unknown", scopeRecorded: false },
  ],
  connectedCount: 2,
  connectable: ["tiktok", "youtube"],
  note: "Reading a network and connecting an account are different things.",
};
const CONNECT_LINK = {
  platform: "tiktok", appId: 41, influencerId: 7,
  connectUrl: "https://www.tiktok.com/v2/auth/authorize?x=1",
  message: "Open this URL in a browser and approve the connection there.",
};
// product_summary, exactly as crates/server/src/mcp_tools.rs sends it: flat,
// with no wrapper and no note. An earlier fixture wrapped it in {product},
// which the server never does — the view matched the fixture and would have
// fallen through to raw JSON against the real thing.
const CREATED = {
  appId: 41, name: "Studio Frame", slug: "studio-frame", productType: "app",
  websiteUrl: "https://studioframe.com", niche: "filmmaking",
  description: null, iconUrl: null, primaryCtaLabel: null, primaryCtaUrl: null,
  externalListingId: null, iosBundleId: null, androidPackage: null,
  createdAt: "2026-08-02T10:00:00Z",
};
const PATCHED = {
  ...CREATED, niche: "lighting for solo shooters", primaryCtaLabel: "Get the presets",
};


test("5a connections: grant stated per connection", async ({ page }) => {
  const errs = await boot(page);
  await result(page, CONNECTIONS);
  expect(await page.locator(".conn-row").count()).toBe(2);
  // unknown must be the mixed tint, never the refusal red.
  const unknown = page.locator(".chip", { hasText: "publish · unknown" });
  await expect(unknown).toHaveClass(/chip-mixed/);
  await expect(page.locator(".chip", { hasText: "comments · no" }).first()).toHaveClass(/chip-negative/);
  expect(await page.locator(".conn-note").count()).toBe(1);
  // Both connectable platforms are already linked, so no Connect row.
  expect(await page.locator("[data-connect]").count()).toBe(0);
  expect(await page.locator(".sec-label").textContent()).toContain("Read-only");
  expect(errs).toEqual([]);
});

test("5a: an unlinked connectable platform offers Connect", async ({ page }) => {
  const errs = await boot(page);
  await result(page, { ...CONNECTIONS, connections: [CONNECTIONS.connections[0]], connectedCount: 1 });
  expect(await page.locator("[data-connect]").count()).toBe(1);
  expect(await page.locator("[data-connect]").getAttribute("data-connect")).toBe("youtube");
  expect(errs).toEqual([]);
});

test("connect_social_account: hands over the link", async ({ page }) => {
  const errs = await boot(page);
  await result(page, CONNECT_LINK);
  expect(await page.locator(".own-title").textContent()).toBe("Waiting for you");
  expect(await page.locator("a.btn").getAttribute("href")).toBe(CONNECT_LINK.connectUrl);
  await expect(page.locator("svg.mk .iris").first()).toBeAttached();
  expect(errs).toEqual([]);
});

test("5b create_product: the row that was written", async ({ page }) => {
  const errs = await boot(page, "create_product");
  await result(page, CREATED);
  expect(await page.locator(".own-head").textContent()).toContain("Studio Frame");
  expect(await page.locator(".own-sub").textContent()).toContain("appId 41");
  expect(await page.locator(".lede-box").textContent()).toContain("no brand playbook");
  expect(await page.locator(".tag").first().textContent()).toBe("Playbook: none");
  expect(await page.locator(".own-tick").count()).toBe(1);
  expect(errs).toEqual([]);
});

test("5b update_product: the row as it now stands", async ({ page }) => {
  const errs = await boot(page, "update_product");
  await result(page, PATCHED);
  // The server returns the whole row, not a list of which columns moved, so
  // the patch view draws its current state rather than an invented diff.
  const keys = await page.locator(".step-k").allTextContents();
  expect(keys).toContain("Niche");
  expect(keys).toContain("CTA label");
  expect(await page.locator(".step-v").nth(keys.indexOf("Niche")).textContent())
    .toContain("lighting for solo shooters");
  expect(await page.locator(".own-tick").count()).toBe(0);
  // Two notes now: the row's own, and the one explaining analyze_product's job.
  expect(await page.locator(".ai-note").first().textContent()).toContain("omitted");
  expect(errs).toEqual([]);
});

test("5a Connect hands the call to the host and swaps in the link", async ({ page }) => {
  const errs = await boot(page);
  // The host answers in-band. invokeTool prefers window.openai.callTool when
  // the host defines it, which is the path this exercises; the postMessage
  // bridge is the other one and has no responder in a bare page.
  await page.evaluate((link) => {
    (window as unknown as { openai: unknown }).openai = {
      callTool: (name: string, args: Record<string, unknown>) => {
        (window as unknown as { __called: unknown }).__called = { name, args };
        return Promise.resolve({ structuredContent: link });
      },
    };
  }, CONNECT_LINK);
  await result(page, { ...CONNECTIONS, connections: [CONNECTIONS.connections[0]], connectedCount: 1 });
  await page.locator("[data-connect]").click();
  await page.waitForTimeout(400);
  expect(await page.evaluate(() => (window as unknown as { __called: unknown }).__called)).toEqual({
    name: "connect_social_account",
    args: { platform: "youtube" },
  });
  expect(await page.locator(".own-title").textContent()).toBe("Waiting for you");
  expect(await page.locator("a.btn").getAttribute("href")).toBe(CONNECT_LINK.connectUrl);
  expect(errs).toEqual([]);
});

test("a spoken row says when it was said, and links to that moment", async ({ page }) => {
  const errs = await boot(page);
  await result(page, MENTIONS);
  await result(page, SPOKEN);
  // The row names the moment...
  expect(await page.locator(".mention-who").first().textContent()).toBe("spoken · 4:12");
  // ...the note repeats it where it is making the claim about provenance...
  expect(await page.locator(".mention-note").first().textContent()).toContain("in the video, at 4:12");
  // ...and YouTube, which honours ?t=, actually jumps there.
  const href = await page.locator(".mgroup").first().locator(".mgroup-link").getAttribute("href");
  expect(href).toBe("https://youtube.com/watch?v=a&t=252s");
  expect(await page.locator(".mgroup-link").first().textContent()).toContain("Open at 4:12");
  expect(errs).toEqual([]);
});

test("an untimed spoken row says nothing rather than guessing", async ({ page }) => {
  const errs = await boot(page);
  const untimed = {
    ...SPOKEN,
    hits: [{
      ...SPOKEN.hits[0],
      excerpts: [{ text: "was nooticr honestly", position: 50, occurrence: 1 }],
    }],
  };
  await result(page, MENTIONS);
  await result(page, untimed);
  expect(await page.locator(".mention-who").first().textContent()).toBe("spoken");
  expect(await page.locator(".mention-note").first().textContent()).toContain("in the video.");
  // No timings, so no ?t= promising a jump that would not happen.
  expect(await page.locator(".mgroup").first().locator(".mgroup-link").getAttribute("href"))
    .toBe("https://youtube.com/watch?v=a");
  expect((await page.locator(".mgroup-link").first().textContent())?.trim()).toBe("Open");
  expect(errs).toEqual([]);
});

test("TikTok shows the moment but does not fake a deep link", async ({ page }) => {
  const errs = await boot(page);
  const tiktok = {
    ...SPOKEN,
    hits: [{
      ...SPOKEN.hits[0],
      post: { ...SPOKEN.hits[0].post, platform: "tiktok", externalUrl: "https://www.tiktok.com/@a/video/1" },
    }],
  };
  await result(page, MENTIONS);
  await result(page, tiktok);
  expect(await page.locator(".mention-who").first().textContent()).toBe("spoken · 4:12");
  // TikTok has no public deep link into a moment: the timecode is shown, the
  // link opens the post, and no ?t= promises a jump it would ignore.
  expect(await page.locator(".mgroup").first().locator(".mgroup-link").getAttribute("href"))
    .toBe("https://www.tiktok.com/@a/video/1");
  expect(errs).toEqual([]);
});

test("3b: the spoken hit opens the video at the line", async ({ page }) => {
  const errs = await boot(page);
  await result(page, MENTIONS);
  await result(page, SPOKEN);
  // The quote is an assertion; the video is the evidence for it, so the top
  // spoken hit's poster plays in place — at the line, not at 0:00.
  await page.locator(".mgroup").first().locator(".mgroup-media.is-playable").click();
  const stage = page.locator(".mgroup").first().locator(".mgroup-stage");
  await expect(stage).toBeVisible();
  // 4:12 = 252s, and the player is told to open there rather than at 0:00.
  expect(await stage.locator(".mp").getAttribute("data-mp-start")).toBe("252");
  expect(await stage.locator("video").count()).toBe(1);
  // The typed-only group has nothing to play and gets no stage.
  expect(await page.locator(".mgroup").nth(1).locator(".mgroup-stage").count()).toBe(0);
  expect(errs).toEqual([]);
});

test("3b: a hit with no video falls back to the thumbnail row", async ({ page }) => {
  const errs = await boot(page);
  const noVideo = {
    ...SPOKEN,
    hits: [{ ...SPOKEN.hits[0], post: { ...SPOKEN.hits[0].post, videoUrl: undefined } }],
  };
  await result(page, MENTIONS);
  await result(page, noVideo);
  // A black rectangle would be worse than the still the row already shows.
  expect(await page.locator(".mgroup-stage").count()).toBe(0);
  expect(await page.locator(".sm-thumb-badged").count()).toBe(1);
  expect(errs).toEqual([]);
});

// ─── The wait, for every tool ───
// The vitest suite checks the plan data; these check the view's own evaluator,
// which is JavaScript inside a template string and cannot be imported.

async function loading(page: Page, name: string, args: Record<string, unknown>) {
  await page.evaluate(
    ([n, a]) => window.postMessage(
      { method: "ui/notifications/tool-input", params: { name: n, arguments: a } }, "*"),
    [name, args] as const,
  );
  await page.waitForTimeout(400);
}

test("the wait prices analyze_post at what it fans out to, not the direct rate", async ({ page }) => {
  const errs = await boot(page);
  await loading(page, "analyze_post", { url: "https://www.tiktok.com/@a/video/1" });
  // 3 = get_post_frames 2 + get_post_transcript 1. nooticr-server bills a
  // direct /mcp analyze_post at 6; this server never makes that call.
  expect(await page.locator(".load-price").textContent()).toBe("3 credits");
  const rows = page.locator(".led-row");
  expect(await rows.count()).toBe(2);
  expect(await rows.nth(0).locator(".led-label").textContent()).toBe("Sampling frames");
  expect(await rows.nth(1).locator(".led-cost").textContent()).toBe("1");
  expect(errs).toEqual([]);
});

test("an all-networks sweep itemises every network it will reach", async ({ page }) => {
  const errs = await boot(page);
  await loading(page, "search_mentions", { term: "nooticr" });
  // Omitting platforms means all nine, which is 21 — the number nothing the
  // caller read told them about.
  await expect(page.locator(".load-centre")).toBeVisible();
  expect(await page.locator(".load-what").textContent()).toBe(String.raw`Sweeping 9 networks for "nooticr"`);
  expect(await page.locator(".load-sub").textContent()).toContain("21 credits committed");
  expect(await page.locator(".led-row").count()).toBe(9);
  // Xiaohongshu costs more upstream, and the ledger says so per line.
  const xhs = page.locator(".led-row", { hasText: "Xiaohongshu" });
  expect(await xhs.locator(".led-cost").textContent()).toBe("5");
  expect(await page.locator(".led-foot").textContent()).toContain("ceiling, not a charge already taken");
  expect(errs).toEqual([]);
});

test("naming the networks reprices the wait", async ({ page }) => {
  const errs = await boot(page);
  await loading(page, "search_mentions", { term: "nooticr", platforms: ["tiktok", "youtube"] });
  // 4 credits is under the line where the wait becomes the screen.
  expect(await page.locator(".load-centre").count()).toBe(0);
  expect(await page.locator(".load-price").textContent()).toBe("4 credits");
  expect(await page.locator(".led-row").count()).toBe(2);
  expect(errs).toEqual([]);
});

test("the wait shows the facts the arguments already carry", async ({ page }) => {
  const errs = await boot(page);
  await loading(page, "get_user_posts", { username: "@studioframe", platform: "tiktok" });
  // Turn 2c, as far as is honest: nothing streams from the server, but the
  // handle whose posts these will be is already known.
  const facts = page.locator(".load-fact");
  expect(await facts.count()).toBeGreaterThan(0);
  expect(await facts.first().textContent()).toBe("@studioframe");
  expect(errs).toEqual([]);
});

test("a url's platform is known before the post is", async ({ page }) => {
  const errs = await boot(page);
  await loading(page, "get_social_media", { url: "https://www.youtube.com/watch?v=a" });
  expect(await page.locator(".load-fact").first().textContent()).toContain("YouTube");
  expect(await page.locator(".load-price").textContent()).toBe("1 credit");
  // One call is not a fan-out worth itemising.
  expect(await page.locator(".led-row").count()).toBe(0);
  expect(errs).toEqual([]);
});

test("a free tool says free rather than nothing", async ({ page }) => {
  const errs = await boot(page);
  await loading(page, "list_social_connections", {});
  expect(await page.locator(".load-price").textContent()).toBe("Free");
  expect(errs).toEqual([]);
});

test("a spoken sweep prices what the tool clamps to, not what was typed", async ({ page }) => {
  const errs = await boot(page);
  // The vitest suite pins these same numbers against the plan data; this is
  // the copy that runs, and the divergence between the two is the whole
  // reason both exist. 3 caption-track networks swept at 2, plus the default
  // 8 transcripts.
  await loading(page, "search_spoken_mentions", { term: "nooticr", niche: "skincare" });
  expect(await page.locator(".load-sub").textContent()).toContain("14 credits committed");
  expect(errs).toEqual([]);
});

test("a network the spoken sweep cannot reach is not a line on its bill", async ({ page }) => {
  const errs = await boot(page);
  // Only the caption-track networks (tiktok, youtube, douyin) are reachable
  // here; the tool filters the rest out before it spends, so pricing three
  // sweeps for this argument quoted two that never run.
  await loading(page, "search_spoken_mentions", {
    term: "nooticr", niche: "skincare", platforms: ["instagram", "reddit", "tiktok"],
  });
  expect(await page.locator(".load-sub").textContent()).toContain("10 credits committed");
  const sweeps = page.locator(".led-row", { hasText: "Sweeping for candidates" });
  expect(await sweeps.count()).toBe(1);
  expect(await sweeps.locator(".led-cost").textContent()).toBe("2");
  expect(errs).toEqual([]);
});

test("a transcript ceiling above the server's own is drawn at the server's", async ({ page }) => {
  const errs = await boot(page);
  // jobs.ts clamps maxTranscripts to MAX_SPOKEN_TRANSCRIPTS (20). Counting
  // the argument as typed drew a 200-credit line for a 20-credit call.
  await loading(page, "search_spoken_mentions", { term: "n", niche: "s", maxTranscripts: 200 });
  expect(await page.locator(".load-sub").textContent()).toContain("26 credits committed");
  const reads = page.locator(".led-row", { hasText: "Transcribing a candidate" });
  expect(await reads.locator(".led-label").textContent()).toContain("×20");
  expect(errs).toEqual([]);
});

test("a named handle is checked once per network, and the watchlist is a ceiling", async ({ page }) => {
  const errs = await boot(page);
  // Two handles across all three networks is six calls, not two.
  await loading(page, "search_spoken_mentions", { term: "n", usernames: ["@a", "@b"] });
  expect(await page.locator(".load-sub").textContent()).toContain("20 credits committed");

  // A watchlist a sandboxed view cannot read is drawn as the ceiling it is
  // clamped to, and says so — it used to be priced at nothing at all.
  await loading(page, "search_spoken_mentions", { term: "n", useWatchlist: true });
  expect(await page.locator(".load-sub").textContent()).toContain("24 credits committed");
  const checks = page.locator(".led-row", { hasText: "Checking a creator" });
  expect(await checks.locator(".led-label").textContent()).toContain("at most");
  expect(errs).toEqual([]);
});

test("no ledger row claims to be finished", async ({ page }) => {
  const errs = await boot(page);
  await loading(page, "search_mentions", { term: "nooticr" });
  // MCP Apps gives the view no progress notification, so a tick here would
  // assert a completion the server never reported. The rows are queued rings.
  expect(await page.locator(".led-dot, .led-mark").count()).toBe(9);
  expect(await page.locator(".led-row.done, .led-row [data-done]").count()).toBe(0);
  expect(errs).toEqual([]);
});

// ─── What the design system's views added ───
// Each of these is a behaviour the Nooticr design system's MCP views draw and
// the template did not, until the port. Pinned so a later restyle keeps them.

test("a cancelled call says what was not charged, from the plan the wait quoted", async ({ page }) => {
  const errs = await boot(page);
  await page.evaluate(() => window.postMessage({ method: "ui/notifications/tool-input", params: {
    name: "search_mentions", arguments: { term: "nooticr", platforms: ["tiktok", "instagram", "youtube", "reddit"] } } }, "*"));
  await page.waitForTimeout(300);
  const quoted = await page.locator(".load-sub").textContent();
  await page.evaluate(() => window.postMessage({ method: "ui/notifications/tool-cancelled", params: { reason: "stopped by user" } }, "*"));
  await page.waitForTimeout(300);
  await expect(page.locator(".nt-commerce-cancel-text")).toHaveText("Cancelled: stopped by user");
  const credits = (quoted ?? "").match(/(\d+) credits/)![1];
  await expect(page.locator(".nt-commerce-cancel-note"))
    .toHaveText(`Nothing was charged — the ${credits} credits quoted were a ceiling, not a charge.`);
  expect(errs).toEqual([]);
});

test("a cancel with no wait before it stays exactly the server's message", async ({ page }) => {
  const errs = await boot(page);
  await page.evaluate(() => window.postMessage({ method: "ui/notifications/tool-cancelled", params: {} }, "*"));
  await page.waitForTimeout(300);
  await expect(page.locator(".nt-commerce-cancel-text")).toHaveText("The tool call was cancelled");
  await expect(page.locator(".nt-commerce-cancel-note")).toHaveCount(0);
  expect(errs).toEqual([]);
});

test("comments page through the whole payload, 25 at a time", async ({ page }) => {
  const errs = await boot(page);
  const comments = Array.from({ length: 60 }, (_, i) => ({ username: `u${i}`, text: `comment ${i}`, likes: 60 - i }));
  await result(page, { comments, themes: [{ keyword: "price", count: 12 }] });
  await expect(page.locator(".nt-feeds-comment")).toHaveCount(25);
  await expect(page.locator(".nt-view-foot")).toContainText("Showing 25 of 60");
  await page.locator("[data-comments-more]").click();
  await expect(page.locator(".nt-feeds-comment")).toHaveCount(50);
  await expect(page.locator("[data-comments-more]")).toHaveText("Show 10 more");
  await page.locator("[data-comments-more]").click();
  await expect(page.locator(".nt-feeds-comment")).toHaveCount(60);
  await expect(page.locator("[data-comments-more]")).toHaveCount(0);
  expect(errs).toEqual([]);
});

test("the trend reads out whichever sweep is under the pointer or the focus", async ({ page }) => {
  const errs = await boot(page);
  const points = [4, 9, 6].map((found, i) => ({ ranAt: `2026-08-0${i + 1}T08:00:00Z`, found, reported: i }));
  await result(page, { term: "nooticr", tool: "mention_trend", points, metric: "found", edgeIsRecordStart: true });
  // The latest sweep by default.
  await expect(page.locator(".nt-signals-readout-v")).toHaveText("6");
  await page.locator('.nt-signals-bar[data-bar="1"]').hover();
  await expect(page.locator(".nt-signals-readout-v")).toHaveText("9");
  await expect(page.locator(".nt-signals-readout")).toContainText("2026-08-02 · 1 new");
  await page.locator('.nt-signals-bar[data-bar="0"]').focus();
  await expect(page.locator(".nt-signals-readout")).toContainText("record starts here");
  await expect(page.locator(".nt-signals-edge")).toHaveCount(1);
  expect(errs).toEqual([]);
});

test("a transcript with cue timings reads timed, and copies what is on screen", async ({ page }) => {
  const errs = await boot(page, "get_post_transcript");
  const transcript = "Hello there. This is nooticr. Goodbye.";
  // get_post_transcript's cues carry no words: only where theirs begin.
  await result(page, { available: true, url: "https://www.youtube.com/watch?v=q1", transcript, language: "en",
    cues: [{ startMs: 0, offset: 0 }, { startMs: 4200, offset: 13 }, { startMs: 65000, offset: 30 }] });
  await expect(page.locator(".nt-signals-cue")).toHaveCount(3);
  expect(await page.locator(".nt-signals-cue-text").allInnerTexts()).toEqual(["Hello there.", "This is nooticr.", "Goodbye."]);
  expect(await page.locator(".nt-signals-cue-at").allInnerTexts()).toEqual(["0:00", "0:04", "1:05"]);
  // YouTube reads a moment off its URL, so each timecode opens the video there.
  expect(await page.locator(".nt-signals-cue-at").nth(2).getAttribute("href")).toBe("https://www.youtube.com/watch?v=q1&t=65s");
  const NL = String.fromCharCode(10);
  expect(await page.locator("[data-tcopy]").getAttribute("data-tcopy"))
    .toBe(["[0:00] Hello there.", "[0:04] This is nooticr.", "[1:05] Goodbye."].join(NL));
  await page.locator('[data-tview="plain"]').click();
  await expect(page.locator(".nt-signals-transcript")).toHaveText(transcript);
  expect(await page.locator("[data-tcopy]").getAttribute("data-tcopy")).toBe(transcript);
  expect(errs).toEqual([]);
});

test("a transcript off YouTube shows its timecodes without promising a jump", async ({ page }) => {
  const errs = await boot(page, "generate_captions");
  await result(page, { transcript: "One. Two.", cues: [{ text: "One.", start_sec: 0, end_sec: 1 }, { text: "Two.", start_sec: 2.5, end_sec: 3 }] });
  expect(await page.locator(".nt-signals-cue-at").allInnerTexts()).toEqual(["0:00", "0:02"]);
  await expect(page.locator("a.nt-signals-cue-at")).toHaveCount(0);
  expect(errs).toEqual([]);
});

test("every compared post keeps its own way back to the post", async ({ page }) => {
  const errs = await boot(page);
  const posts = [1, 2].map((i) => ({ platform: "tiktok", caption: `p${i}`, externalUrl: `https://www.tiktok.com/@a/video/${i}`, views: i * 10, comments: i }));
  await result(page, { posts, comparison: { winner: 2, winnerReason: "It asks.", nextTest: "Ask sooner." } });
  await expect(page.locator(".nt-view-desc")).toHaveText("Post #2 performed best");
  expect(await page.locator(".nt-feeds-cmp-row a").evaluateAll((a) => a.map((x) => x.getAttribute("href"))))
    .toEqual(["https://www.tiktok.com/@a/video/1", "https://www.tiktok.com/@a/video/2"]);
  await expect(page.locator(".nt-feeds-cmp-row.is-win")).toContainText("Best");
  await expect(page.locator(".nt-feeds-callout")).toContainText("Ask sooner.");
  expect(errs).toEqual([]);
});

test("a listing opens as its own page within the card, with the way back", async ({ page }) => {
  const errs = await boot(page, "scan_amazon_category");
  await result(page, {
    marketplace: "amazon", domain: "www.amazon.fr", query: "skillets", complete: false, progress: { done: 3, total: 10 },
    products: [
      { asin: "A1", brand: "Lodge", title: "Lodge skillet", rating: 4.6, ratingCount: 900, price: "€34.90", ratingHistogram: { 5: 70, 1: 5 } },
      { asin: "A2", brand: "Staub", title: "Staub pan", rating: 4.7, ratingCount: 100, price: "€119.00" },
    ],
  });
  // A running scan says how far it has got.
  await expect(page.locator(".nt-commerce-running")).toHaveText("Collecting 3/10");
  expect(await page.locator(".nt-progress").getAttribute("aria-valuenow")).toBe("30");
  await page.locator('[data-amz-open="A1"]').click();
  await expect(page.locator(".amz-detail")).toContainText("Lodge skillet");
  await expect(page.locator(".amz-tile")).toHaveCount(0);
  await page.locator("[data-amz-back]").click();
  await expect(page.locator(".amz-tile")).toHaveCount(2);
  expect(errs).toEqual([]);
});

test("a scan the host stopped polling says where it stopped, not that it is still collecting", async ({ page }) => {
  const errs = await boot(page, "scan_amazon_category");
  await result(page, {
    marketplace: "amazon", domain: "www.amazon.de", query: "nike", complete: false, stopped: true, progress: { done: 4, total: 10 },
    products: [{ asin: "A1", brand: "Nike", title: "Air Force 1", rating: 4.6, ratingCount: 900, price: "€119.00" }],
  });
  await expect(page.locator(".nt-commerce-stopped")).toHaveText("Stopped at 4/10");
  await expect(page.locator(".nt-commerce-running")).toHaveCount(0);
  await expect(page.locator(".nt-progress")).toHaveCount(0);
  expect(errs).toEqual([]);
});

test("a claim's evidence id lands on its review, badged as the one cited", async ({ page }) => {
  const errs = await boot(page, "show_amazon_category_insights");
  await result(page, {
    view: "insights", marketplace: "amazon", category: "Skillets",
    products: [{ asin: "A1", brand: "Lodge", title: "Lodge", reviews: [
      { id: "R1", rating: 5, title: "Great", body: "Great pan" }, { id: "R2", rating: 1, title: "Rust", body: "Rusted" }] }],
    barriers: [{ label: "Rust", strength: "strong", evidence: ["R2"] }],
  });
  await page.locator('[data-amz-ev="R2"]').click();
  await expect(page.locator(".amz-rev").first()).toContainText("Rusted");
  await expect(page.locator(".amz-rev").first().locator(".nt-commerce-rev-pin")).toHaveText("Cited");
  await expect(page.locator('[data-amz-star=""] b')).toHaveText("2");
  expect(errs).toEqual([]);
});

test("Compare carries its price on its face", async ({ page }) => {
  const errs = await boot(page);
  const posts = [1, 2].map((i) => ({ platform: "tiktok", caption: `p${i}`, externalUrl: `https://www.tiktok.com/@a/video/${i}`,
    videoUrl: "https://mcp.nooticr.com/media/x.mp4", contentType: "video" }));
  await result(page, { posts });
  await page.locator(".mp-pick").nth(0).click();
  await page.locator(".mp-pick").nth(1).click();
  await expect(page.locator("#pickgo")).toContainText("Compare");
  await expect(page.locator("#pickgo .nt-feeds-cr")).toHaveText("1 cr");
  await expect(page.locator("#pickgo")).toBeEnabled();
  expect(errs).toEqual([]);
});

test("the view takes the host's theme over the OS's", async ({ page }) => {
  await page.emulateMedia({ colorScheme: "light" });
  const errs = await boot(page);
  expect(await page.evaluate(() => document.documentElement.getAttribute("data-theme"))).toBe("light");
  await page.evaluate(() => window.postMessage({ method: "ui/notifications/host-context-changed", params: { theme: "dark" } }, "*"));
  await page.waitForTimeout(100);
  expect(await page.evaluate(() => document.documentElement.getAttribute("data-theme"))).toBe("dark");
  expect(await page.evaluate(() => getComputedStyle(document.documentElement).colorScheme)).toBe("dark");
  expect(await page.evaluate(() => getComputedStyle(document.documentElement).getPropertyValue("--background").trim())).toBe("#0a0a0a");
  expect(errs).toEqual([]);
});

// ─── A card's own buttons, answered by a host that runs them in-band ───
//
// A host hands a view's tools/call result back to the view and nowhere else,
// and most report a tool's refusal as a result with isError rather than as a
// rejection. So what the button does with the answer is the whole feature.

/** A host that runs every call the card makes and answers with `reply`. */
async function inBandHost(page: Page, reply: unknown) {
  await page.evaluate((r) => {
    const w = window as unknown as Record<string, unknown>;
    w.__called = [];
    w.openai = {
      callTool: (name: string, args: unknown) => {
        (w.__called as unknown[]).push({ name, args });
        return Promise.resolve(r);
      },
    };
  }, reply);
}
const calledTools = (page: Page) => page.evaluate(() => (window as unknown as { __called: unknown }).__called);
const refusal = (text: string) => ({ isError: true, content: [{ type: "text", text }] });
const TWO_POSTS = [1, 2].map((i) => ({ platform: "tiktok", caption: `p${i}`, externalUrl: `https://www.tiktok.com/@a/video/${i}`,
  videoUrl: "https://mcp.nooticr.com/media/x.mp4", contentType: "video" }));

test("a Compare the tool refused says why, rather than Sent", async ({ page }) => {
  const errs = await boot(page);
  await inBandHost(page, refusal("compare_posts failed: Not enough nooticr credits — 1 needed, 0 left."));
  await result(page, { posts: TWO_POSTS });
  await page.locator(".mp-pick").nth(0).click();
  await page.locator(".mp-pick").nth(1).click();
  await page.locator("#pickgo").click();
  await expect(page.locator("#pickhint")).toHaveText("compare_posts failed: Not enough nooticr credits — 1 needed, 0 left.");
  await expect(page.locator("#pickgo")).toContainText("Compare");
  await expect(page.locator("#pickgo")).not.toContainText(/Sent|Copied/);
  expect(await calledTools(page)).toEqual([{ name: "compare_posts", args: { urls: TWO_POSTS.map((p) => p.externalUrl) } }]);
  expect(errs).toEqual([]);
});

test("an action under a post the tool refused says why under its row", async ({ page }) => {
  const errs = await boot(page);
  await inBandHost(page, refusal("write_hooks failed: that post is private"));
  await result(page, { analysis: { summary: "A hook-led demo." }, post: TWO_POSTS[0] });
  await page.locator('.ai-btn[data-ai="write_hooks"]').click();
  await expect(page.locator(".nt-call-error")).toHaveText("write_hooks failed: that post is private");
  await expect(page.locator('.ai-btn[data-ai="write_hooks"]')).toContainText("Failed");
  // A check beside "Failed" would say both things at once: the alert glyph.
  expect(await page.locator('.ai-btn[data-ai="write_hooks"] .nt-ai-ico').innerHTML()).toContain("m21.73 18-8-14");
  expect(errs).toEqual([]);
});

test("Load more appends the next page to the list it was pressed under", async ({ page }) => {
  const errs = await boot(page);
  const next = {
    term: "nooticr", totalMentions: 341, byPlatform: MENTIONS.byPlatform, hasMore: false, nextOffset: null,
    threads: [{ post: { platform: "tiktok", title: "A third post", externalUrl: "https://tiktok.com/@x/video/3", views: 5000 },
      mentionCount: 1, mentions: [{ id: "c3", username: "zed", text: "nooticr found this one on page two", likes: 3 }] }],
  };
  await inBandHost(page, { structuredContent: next });
  await result(page, { ...MENTIONS, hasMore: true, nextOffset: 2 });
  await expect(page.locator(".mgroup")).toHaveCount(2);
  await page.locator(".mention-more").click();
  await expect(page.locator(".mgroup")).toHaveCount(3);
  await expect(page.locator(".mentions")).toContainText(["we switched to nooticr last month"]);
  await expect(page.locator(".mgroups")).toContainText("nooticr found this one on page two");
  await expect(page.locator(".mention-more")).toHaveCount(0);
  expect(await calledTools(page)).toEqual([{ name: "search_mentions", args: { term: "nooticr", offset: 2 } }]);
  expect(errs).toEqual([]);
});

test("Analyse these draws what analyze_comments read", async ({ page }) => {
  const errs = await boot(page);
  await inBandHost(page, { structuredContent: {
    url: "https://reddit.com/r/x/1", platform: "reddit", commentCount: 2,
    comments: [{ username: "dw_makes", text: "we switched to nooticr last month", likes: 412 }, { username: "b", text: "same here", likes: 3 }],
    themes: [{ keyword: "switch", count: 2 }],
  } });
  await result(page, MENTIONS);
  await page.locator(".mention-pick").first().click();
  await page.locator("#pickgo").click();
  await expect(page.locator(".nt-feeds-comment")).toHaveCount(2);
  await expect(page.locator(".mgroups")).toHaveCount(0);
  expect(await calledTools(page)).toEqual([{ name: "analyze_comments", args: { url: "https://reddit.com/r/x/1", limit: 20 } }]);
  expect(errs).toEqual([]);
});

test("Analyse the product names its own row and keeps the card while the job runs", async ({ page }) => {
  const errs = await boot(page, "create_product");
  await inBandHost(page, { structuredContent: { jobId: "job-1", state: "pending" } });
  await result(page, CREATED);
  await page.locator("[data-analyze-product]").click();
  await expect(page.locator("[data-analyze-product]")).toContainText("Analysis started");
  await expect(page.locator("[data-analyze-product]")).toBeDisabled();
  await expect(page.locator(".own-head")).toContainText("Studio Frame");
  await expect(page.locator(".nt-view-json")).toHaveCount(0);
  expect(await calledTools(page)).toEqual([{ name: "analyze_product", args: { appId: 41 } }]);
  expect(errs).toEqual([]);
});
