/**
 * Browser end-to-end tests for the surfaces the design board added:
 * the mark that does the waiting, the quiet skeleton and the price on the
 * face of the wait; the merged typed+spoken mention feed; and the two
 * own-account screens.
 *
 * These are here rather than in vitest for the same reason ui-template.e2e.ts
 * is: the template is one 3,000-line string of DOM-building JavaScript, and
 * the things worth pinning about it — that a handler fires, that a click
 * redraws the right screen, that no page error is thrown — are only true in a
 * real browser. Every test asserts an empty console as well as its own
 * subject, because a thrown TypeError in one of these renderers leaves the
 * previous screen on display and would otherwise pass silently.
 *
 *   npx playwright test tests/e2e/ui-views.e2e.ts
 */
import { test, expect, type Page } from "@playwright/test";
import { uiTemplateFor } from "../../src/shared/tools.js";

// The substituted view, not the raw template: the raw one still carries its
// __NOOTICR_PLANS__ placeholder, so a test on it would pass with no prices
// and no ledger while the real view was broken.
const NOOTICR_UI_TEMPLATE = uiTemplateFor();

const MENTIONS = {
  term: "nooticr",
  totalMentions: 341,
  byPlatform: { reddit: 61, youtube: 101, tiktok: 191 },
  threads: [
    { post: { platform: "reddit", title: "Anyone else moved their brand-monitoring stack onto an MCP server?", externalUrl: "https://reddit.com/r/x/1", views: 25100 },
      mentionCount: 1, postIsAboutTerm: true,
      mentions: [{ id: "c1", username: "dw_makes", text: "we switched to nooticr last month", likes: 412, replies: 8, postedAt: "2026-09-05T19:25:00Z", hits: 2 }] },
    { post: { platform: "youtube", title: "I tested 6 social listening tools for a week", externalUrl: "https://youtube.com/watch?v=a", views: 96000 },
      mentionCount: 1,
      mentions: [{ id: "c2", username: "aliceb.edits", text: "he says nooticr at 4:12 for anyone skipping", likes: 244, replies: 19, postedAt: "2026-09-05T08:14:00Z" }] },
  ],
  unavailable: [],
};

const SPOKEN = {
  term: "nooticr",
  platforms: ["youtube", "tiktok"],
  candidatesConsidered: 26, transcribed: 14, transcriptsAvailable: 14, matched: 1,
  maxTranscripts: 20, ceilingReached: false,
  hits: [{
    post: { platform: "youtube", title: "I tested 6 social listening tools for a week", externalUrl: "https://youtube.com/watch?v=a", views: 96000, thumbnailUrl: "https://mcp.nooticr.com/media/t.jpg", videoUrl: "https://mcp.nooticr.com/media/x.mp4", contentType: "video", duration: 608, postedAt: "2026-09-04T18:02:00Z" },
    postId: "post:youtube:a", matchCount: 1,
    excerpts: [{ text: "the only one that didn't try to sell me an opinion was nooticr", position: 1200, occurrence: 1, startMs: 252340, timecode: "4:12" }],
    wordCount: 1840, language: "en", autoGenerated: true,
  }],
  unavailable: [],
};

async function boot(page: Page, tool = "") {
  const errs: string[] = [];
  page.on("pageerror", (e) => errs.push(String(e)));
  page.on("console", (m) => { if (m.type() === "error") errs.push(m.text()); });
  // Each tool is served at its own resource URI with its name baked in, which
  // is how the product view tells a create from a patch.
  await page.setContent(tool ? uiTemplateFor(tool) : NOOTICR_UI_TEMPLATE);
  return errs;
}
async function result(page: Page, d: unknown) {
  await page.evaluate((x) => window.postMessage({ method: "ui/notifications/tool-result", params: { structuredContent: x } }, "*"), d);
  await page.waitForTimeout(400);
}

test("loading: inline mark under 6 credits", async ({ page }) => {
  const errs = await boot(page);
  await page.evaluate(() => window.postMessage({ method: "ui/notifications/tool-input", params: { name: "get_social_media", arguments: { url: "https://tiktok.com/x" } } }, "*"));
  await page.waitForTimeout(400);
  await expect(page.locator("svg.mk .iris").first()).toBeVisible();
  expect(await page.locator(".load-price").textContent()).toBe("1 credit");
  expect(await page.locator(".load-centre").count()).toBe(0);
  expect(errs).toEqual([]);
});

test("loading: centred mark over 6 credits", async ({ page }) => {
  const errs = await boot(page);
  await page.evaluate(() => window.postMessage({ method: "ui/notifications/tool-input", params: { name: "search_mentions", arguments: { term: "nooticr" } } }, "*"));
  await page.waitForTimeout(400);
  await expect(page.locator(".load-centre")).toBeVisible();
  expect(await page.locator(".load-sub").textContent()).toContain("21 credits committed");
  expect(await page.locator(".load-what").textContent()).toBe(String.raw`Sweeping 9 networks for "nooticr"`);
  expect(errs).toEqual([]);
});

test("idle mark is the same mark at rest", async ({ page }) => {
  const errs = await boot(page);
  await page.waitForTimeout(300);
  expect(await page.locator("svg.mk").count()).toBe(1);
  expect(await page.locator("svg.mk .iris").count()).toBe(0);
  expect(errs).toEqual([]);
});

test("merged feed: both sweeps, one screen", async ({ page }) => {
  const errs = await boot(page);
  await result(page, MENTIONS);
  await result(page, SPOKEN);
  await page.waitForTimeout(300);
  expect(await page.locator(".mention-total").textContent()).toBe("341 typed · 1 spoken");
  expect(await page.locator("[data-source]").count()).toBe(3);
  expect(await page.locator(".mgroup-about").first().textContent()).toBe("said out loud");
  expect(await page.locator(".mention").count()).toBe(3);
  // Spoken group leads.
  expect(await page.locator(".mgroup").first().getAttribute("data-platform")).toBe("youtube");
  expect(errs).toEqual([]);
});

test("merged feed: source toggle and mixed selection", async ({ page }) => {
  const errs = await boot(page);
  await result(page, MENTIONS);
  await result(page, SPOKEN);
  await page.locator('[data-source="spoken"]').click();
  await page.waitForTimeout(250);
  expect(await page.locator(".mention").count()).toBe(1);
  await page.locator('[data-source="both"]').click();
  await page.waitForTimeout(250);
  // one spoken + one typed
  await page.locator(".mention-pick").nth(0).check();
  await page.locator(".mention-pick").nth(1).check();
  await page.waitForTimeout(250);
  expect(await page.locator("#pickhint").textContent()).toBe("1 spoken, 1 typed");
  expect(errs).toEqual([]);
});

test("spoken-only empty result still draws the funnel", async ({ page }) => {
  const errs = await boot(page);
  await result(page, MENTIONS);
  await result(page, { ...SPOKEN, matched: 0, hits: [] });
  await page.locator('[data-source="spoken"]').click();
  await page.waitForTimeout(250);
  expect(await page.locator(".empty-state .text").textContent()).toBe("Nobody said it out loud");
  expect(await page.locator(".card-body .section-text").textContent()).toContain("14 transcribed");
  expect(errs).toEqual([]);
});

const CONNECTIONS = {
  connections: [
    { appId: 41, appName: "Studio Frame", influencerId: 7, influencerName: "Studio Frame",
      platform: "tiktok", accountName: "studioframe", status: "active",
      canReadAccount: "yes", canPublishPost: "yes", canManageComments: "no", scopeRecorded: true },
    { appId: 41, appName: "Studio Frame", influencerId: 8, influencerName: "Paper & Pixel",
      platform: "youtube", accountName: "paperandpixel", status: "active",
      canReadAccount: "yes", canPublishPost: "unknown", canManageComments: "unknown", scopeRecorded: false },
  ],
  connectedCount: 2,
  connectable: ["tiktok", "youtube"],
  note: "Reading a network and connecting an account are different things.",
};
const CONNECT_LINK = {
  platform: "tiktok", appId: 41, influencerId: 7,
  connectUrl: "https://www.tiktok.com/v2/auth/authorize?x=1",
  message: "Open this URL in a browser and approve the connection there.",
};
// product_summary, exactly as crates/server/src/mcp_tools.rs sends it: flat,
// with no wrapper and no note. An earlier fixture wrapped it in {product},
// which the server never does — the view matched the fixture and would have
// fallen through to raw JSON against the real thing.
const CREATED = {
  appId: 41, name: "Studio Frame", slug: "studio-frame", productType: "app",
  websiteUrl: "https://studioframe.com", niche: "filmmaking",
  description: null, iconUrl: null, primaryCtaLabel: null, primaryCtaUrl: null,
  externalListingId: null, iosBundleId: null, androidPackage: null,
  createdAt: "2026-08-02T10:00:00Z",
};
const PATCHED = {
  ...CREATED, niche: "lighting for solo shooters", primaryCtaLabel: "Get the presets",
};


test("5a connections: grant stated per connection", async ({ page }) => {
  const errs = await boot(page);
  await result(page, CONNECTIONS);
  expect(await page.locator(".conn-row").count()).toBe(2);
  // unknown must be the mixed tint, never the refusal red.
  const unknown = page.locator(".chip", { hasText: "publish · unknown" });
  await expect(unknown).toHaveClass(/chip-mixed/);
  await expect(page.locator(".chip", { hasText: "comments · no" }).first()).toHaveClass(/chip-negative/);
  expect(await page.locator(".conn-note").count()).toBe(1);
  // Both connectable platforms are already linked, so no Connect row.
  expect(await page.locator("[data-connect]").count()).toBe(0);
  expect(await page.locator(".sec-label").textContent()).toContain("Read-only");
  expect(errs).toEqual([]);
});

test("5a: an unlinked connectable platform offers Connect", async ({ page }) => {
  const errs = await boot(page);
  await result(page, { ...CONNECTIONS, connections: [CONNECTIONS.connections[0]], connectedCount: 1 });
  expect(await page.locator("[data-connect]").count()).toBe(1);
  expect(await page.locator("[data-connect]").getAttribute("data-connect")).toBe("youtube");
  expect(errs).toEqual([]);
});

test("connect_social_account: hands over the link", async ({ page }) => {
  const errs = await boot(page);
  await result(page, CONNECT_LINK);
  expect(await page.locator(".own-title").textContent()).toBe("Waiting for you");
  expect(await page.locator("a.btn").getAttribute("href")).toBe(CONNECT_LINK.connectUrl);
  await expect(page.locator("svg.mk .iris").first()).toBeAttached();
  expect(errs).toEqual([]);
});

test("5b create_product: the row that was written", async ({ page }) => {
  const errs = await boot(page, "create_product");
  await result(page, CREATED);
  expect(await page.locator(".own-head").textContent()).toContain("Studio Frame");
  expect(await page.locator(".own-sub").textContent()).toContain("appId 41");
  expect(await page.locator(".lede-box").textContent()).toContain("no brand playbook");
  expect(await page.locator(".tag").first().textContent()).toBe("playbook: none");
  expect(await page.locator(".own-tick").count()).toBe(1);
  expect(errs).toEqual([]);
});

test("5b update_product: the row as it now stands", async ({ page }) => {
  const errs = await boot(page, "update_product");
  await result(page, PATCHED);
  // The server returns the whole row, not a list of which columns moved, so
  // the patch view draws its current state rather than an invented diff.
  const keys = await page.locator(".step-k").allTextContents();
  expect(keys).toContain("Niche");
  expect(keys).toContain("CTA label");
  expect(await page.locator(".step-v").nth(keys.indexOf("Niche")).textContent())
    .toContain("lighting for solo shooters");
  expect(await page.locator(".own-tick").count()).toBe(0);
  expect(await page.locator(".ai-note").textContent()).toContain("omitted");
  expect(errs).toEqual([]);
});

test("5a Connect hands the call to the host and swaps in the link", async ({ page }) => {
  const errs = await boot(page);
  // The host answers in-band. invokeTool prefers window.openai.callTool when
  // the host defines it, which is the path this exercises; the postMessage
  // bridge is the other one and has no responder in a bare page.
  await page.evaluate((link) => {
    (window as unknown as { openai: unknown }).openai = {
      callTool: (name: string, args: Record<string, unknown>) => {
        (window as unknown as { __called: unknown }).__called = { name, args };
        return Promise.resolve({ structuredContent: link });
      },
    };
  }, CONNECT_LINK);
  await result(page, { ...CONNECTIONS, connections: [CONNECTIONS.connections[0]], connectedCount: 1 });
  await page.locator("[data-connect]").click();
  await page.waitForTimeout(400);
  expect(await page.evaluate(() => (window as unknown as { __called: unknown }).__called)).toEqual({
    name: "connect_social_account",
    args: { platform: "youtube" },
  });
  expect(await page.locator(".own-title").textContent()).toBe("Waiting for you");
  expect(await page.locator("a.btn").getAttribute("href")).toBe(CONNECT_LINK.connectUrl);
  expect(errs).toEqual([]);
});

test("a spoken row says when it was said, and links to that moment", async ({ page }) => {
  const errs = await boot(page);
  await result(page, MENTIONS);
  await result(page, SPOKEN);
  // The row names the moment...
  expect(await page.locator(".mention-who").first().textContent()).toBe("spoken · 4:12");
  // ...the note repeats it where it is making the claim about provenance...
  expect(await page.locator(".mention-note").first().textContent()).toContain("in the video, at 4:12");
  // ...and YouTube, which honours ?t=, actually jumps there.
  const href = await page.locator(".mgroup").first().locator(".mgroup-link").getAttribute("href");
  expect(href).toBe("https://youtube.com/watch?v=a&t=252s");
  expect(await page.locator(".mgroup-link").first().textContent()).toContain("Open at 4:12");
  expect(errs).toEqual([]);
});

test("an untimed spoken row says nothing rather than guessing", async ({ page }) => {
  const errs = await boot(page);
  const untimed = {
    ...SPOKEN,
    hits: [{
      ...SPOKEN.hits[0],
      excerpts: [{ text: "was nooticr honestly", position: 50, occurrence: 1 }],
    }],
  };
  await result(page, MENTIONS);
  await result(page, untimed);
  expect(await page.locator(".mention-who").first().textContent()).toBe("spoken");
  expect(await page.locator(".mention-note").first().textContent()).toContain("in the video.");
  // No timings, so no ?t= promising a jump that would not happen.
  expect(await page.locator(".mgroup").first().locator(".mgroup-link").getAttribute("href"))
    .toBe("https://youtube.com/watch?v=a");
  expect(await page.locator(".mgroup-link").first().textContent()).toContain("Open ↗");
  expect(errs).toEqual([]);
});

test("TikTok shows the moment but does not fake a deep link", async ({ page }) => {
  const errs = await boot(page);
  const tiktok = {
    ...SPOKEN,
    hits: [{
      ...SPOKEN.hits[0],
      post: { ...SPOKEN.hits[0].post, platform: "tiktok", externalUrl: "https://www.tiktok.com/@a/video/1" },
    }],
  };
  await result(page, MENTIONS);
  await result(page, tiktok);
  expect(await page.locator(".mention-who").first().textContent()).toBe("spoken · 4:12");
  // TikTok has no public deep link into a moment: the timecode is shown, the
  // link opens the post, and no ?t= promises a jump it would ignore.
  expect(await page.locator(".mgroup").first().locator(".mgroup-link").getAttribute("href"))
    .toBe("https://www.tiktok.com/@a/video/1");
  expect(errs).toEqual([]);
});

test("3b: the spoken hit opens the video at the line", async ({ page }) => {
  const errs = await boot(page);
  await result(page, MENTIONS);
  await result(page, SPOKEN);
  // The quote is an assertion; the video is the evidence for it, so the top
  // spoken hit carries a real player rather than a still.
  const stage = page.locator(".mgroup").first().locator(".mgroup-stage");
  await expect(stage).toBeVisible();
  // 4:12 = 252s, and the player is told to open there rather than at 0:00.
  expect(await stage.locator(".mp").getAttribute("data-mp-start")).toBe("252");
  expect(await stage.locator("video").count()).toBe(1);
  // The typed-only group has nothing to play and gets no stage.
  expect(await page.locator(".mgroup").nth(1).locator(".mgroup-stage").count()).toBe(0);
  expect(errs).toEqual([]);
});

test("3b: a hit with no video falls back to the thumbnail row", async ({ page }) => {
  const errs = await boot(page);
  const noVideo = {
    ...SPOKEN,
    hits: [{ ...SPOKEN.hits[0], post: { ...SPOKEN.hits[0].post, videoUrl: undefined } }],
  };
  await result(page, MENTIONS);
  await result(page, noVideo);
  // A black rectangle would be worse than the still the row already shows.
  expect(await page.locator(".mgroup-stage").count()).toBe(0);
  expect(await page.locator(".sm-thumb-badged").count()).toBe(1);
  expect(errs).toEqual([]);
});

// ─── The wait, for every tool ───
// The vitest suite checks the plan data; these check the view's own evaluator,
// which is JavaScript inside a template string and cannot be imported.

async function loading(page: Page, name: string, args: Record<string, unknown>) {
  await page.evaluate(
    ([n, a]) => window.postMessage(
      { method: "ui/notifications/tool-input", params: { name: n, arguments: a } }, "*"),
    [name, args] as const,
  );
  await page.waitForTimeout(400);
}

test("the wait prices analyze_post at what it fans out to, not the direct rate", async ({ page }) => {
  const errs = await boot(page);
  await loading(page, "analyze_post", { url: "https://www.tiktok.com/@a/video/1" });
  // 3 = get_post_frames 2 + get_post_transcript 1. nooticr-server bills a
  // direct /mcp analyze_post at 6; this server never makes that call.
  expect(await page.locator(".load-price").textContent()).toBe("3 credits");
  const rows = page.locator(".led-row");
  expect(await rows.count()).toBe(2);
  expect(await rows.nth(0).locator(".led-label").textContent()).toBe("Sampling frames");
  expect(await rows.nth(1).locator(".led-cost").textContent()).toBe("1");
  expect(errs).toEqual([]);
});

test("an all-networks sweep itemises every network it will reach", async ({ page }) => {
  const errs = await boot(page);
  await loading(page, "search_mentions", { term: "nooticr" });
  // Omitting platforms means all nine, which is 21 — the number nothing the
  // caller read told them about.
  await expect(page.locator(".load-centre")).toBeVisible();
  expect(await page.locator(".load-what").textContent()).toBe(String.raw`Sweeping 9 networks for "nooticr"`);
  expect(await page.locator(".load-sub").textContent()).toContain("21 credits committed");
  expect(await page.locator(".led-row").count()).toBe(9);
  // Xiaohongshu costs more upstream, and the ledger says so per line.
  const xhs = page.locator(".led-row", { hasText: "Xiaohongshu" });
  expect(await xhs.locator(".led-cost").textContent()).toBe("5");
  expect(await page.locator(".led-foot").textContent()).toContain("ceiling, not a charge already taken");
  expect(errs).toEqual([]);
});

test("naming the networks reprices the wait", async ({ page }) => {
  const errs = await boot(page);
  await loading(page, "search_mentions", { term: "nooticr", platforms: ["tiktok", "youtube"] });
  // 4 credits is under the line where the wait becomes the screen.
  expect(await page.locator(".load-centre").count()).toBe(0);
  expect(await page.locator(".load-price").textContent()).toBe("4 credits");
  expect(await page.locator(".led-row").count()).toBe(2);
  expect(errs).toEqual([]);
});

test("the wait shows the facts the arguments already carry", async ({ page }) => {
  const errs = await boot(page);
  await loading(page, "get_user_posts", { username: "@studioframe", platform: "tiktok" });
  // Turn 2c, as far as is honest: nothing streams from the server, but the
  // handle whose posts these will be is already known.
  const facts = page.locator(".load-fact");
  expect(await facts.count()).toBeGreaterThan(0);
  expect(await facts.first().textContent()).toBe("@studioframe");
  expect(errs).toEqual([]);
});

test("a url's platform is known before the post is", async ({ page }) => {
  const errs = await boot(page);
  await loading(page, "get_social_media", { url: "https://www.youtube.com/watch?v=a" });
  expect(await page.locator(".load-fact").first().textContent()).toContain("YouTube");
  expect(await page.locator(".load-price").textContent()).toBe("1 credit");
  // One call is not a fan-out worth itemising.
  expect(await page.locator(".led-row").count()).toBe(0);
  expect(errs).toEqual([]);
});

test("a free tool says free rather than nothing", async ({ page }) => {
  const errs = await boot(page);
  await loading(page, "list_social_connections", {});
  expect(await page.locator(".load-price").textContent()).toBe("Free");
  expect(errs).toEqual([]);
});

test("no ledger row claims to be finished", async ({ page }) => {
  const errs = await boot(page);
  await loading(page, "search_mentions", { term: "nooticr" });
  // MCP Apps gives the view no progress notification, so a tick here would
  // assert a completion the server never reported. The rows are queued rings.
  expect(await page.locator(".led-dot, .led-mark").count()).toBe(9);
  expect(await page.locator(".led-row.done, .led-row [data-done]").count()).toBe(0);
  expect(errs).toEqual([]);
});
