/**
 * Which tools belong to which backend capability, and the checks that keep
 * their descriptions honest.
 *
 * The platform lists themselves are NOT here. They are generated by
 * nooticr-server from the constants beside its dispatchers and vendored as
 * `vendor/platform-capabilities.json` — because every platform claim in this
 * repo is a claim about code in that one, and hand-copying them is exactly how
 * they drifted: search_creators advertised YouTube and Douyin its own enum
 * rejected, get_post_comments served Reddit and Weibo and named neither, and
 * get_post_transcript claimed a TikTok/YouTube ceiling it does not have.
 *
 * What stays here is the mapping from tool to capability, which is this repo's
 * own business: the server knows what it can reach, and only this side knows
 * which tool description is making the claim.
 *
 * Lives under tests/ rather than src/ because nothing at runtime reads it, and
 * package.json ships only `dist` — a runtime import reaching into `vendor/`
 * would resolve in this checkout and crash in the published package.
 */

import manifest from "../vendor/platform-capabilities.json" with { type: "json" };

/** One capability as nooticr-server publishes it. */
export type ServedCapability = {
  readonly source: string;
  readonly platforms: readonly string[];
  /**
   * False when the dispatcher's fallback does real work, so the list is a fast
   * path rather than a limit and no description may present it as the
   * boundary. get_post_transcript did, and was wrong for every platform whose
   * audio is transcribed by listening.
   */
  readonly listIsCeiling: boolean;
  readonly note?: string;
  /** Swept, but with no comment endpoint — silence there is the API, not the audience. */
  readonly commentsUnavailable?: readonly string[];
};

export const SERVED: Readonly<Record<string, ServedCapability>> = manifest;

/** This repo's half: which tools speak for a capability, and how loudly. */
export type Capability = {
  /**
   * Tools whose description enumerates platforms. These must name every
   * platform the capability serves and no others — the check that catches a
   * capability the server has and no host is told about.
   */
  readonly enumerating: readonly string[];
  /** Tools backed by it that do not list platforms in prose. */
  readonly quiet?: readonly string[];
  /**
   * Set for capabilities with no upstream fetch at all, where "platforms" is a
   * target or a runtime-configured link rather than something reachable.
   */
  readonly platforms?: readonly string[];
  readonly source?: string;
  readonly listIsCeiling?: boolean;
  readonly caveats?: Readonly<Record<string, string>>;
  readonly beyondList?: string;
};

/**
 * Which tools speak for which capability. Names must match a key in the
 * vendored manifest, except the two kinds below that have no upstream fetch.
 */
export const CAPABILITIES: Readonly<Record<string, Capability>> = {
  postDetail: {
    enumerating: ["get_social_media", "understand_social_post"],
    quiet: ["analyze_post", "analyze_post_fast", "compare_posts", "get_post_frames"],
  },
  comments: {
    enumerating: ["get_post_comments"],
    quiet: ["analyze_comments"],
  },
  userPosts: {
    enumerating: ["analyze_creator_profile"],
    quiet: [
      "get_user_posts",
      "find_hook_pattern",
      "watch_creator",
      "unwatch_creator",
      "track_competitor",
      "catch_up_watchlist",
      "what_should_i_make_next",
      "why_did_this_underperform",
      "answer_my_audience",
    ],
  },
  creatorSearch: {
    enumerating: ["search_creators", "who_should_i_work_with"],
  },
  similarCreators: {
    enumerating: ["get_similar_creators"],
  },
  sounds: {
    enumerating: ["discover_sounds"],
  },
  discovery: {
    enumerating: [],
    quiet: ["discover_social_posts", "niche_report", "discover_hashtags"],
  },
  transcript: {
    enumerating: [],
    quiet: ["get_post_transcript"],
  },
  mentions: {
    enumerating: ["search_mentions"],
    quiet: ["create_brand_watch", "search_spoken_mentions"],
    caveats: { xiaohongshu: "post text only — its comments cannot be fetched" },
  },

  /**
   * Writing FOR a platform rather than reading from one. No upstream fetch, so
   * nothing here can be unreachable — a target is just a shape text is written
   * into. Local, because the server has no capability for it.
   */
  authoringTarget: {
    source: "no upstream call — the platform is a target, not a source",
    platforms: [
      "tiktok",
      "instagram",
      "youtube",
      "douyin",
      "xiaohongshu",
      "twitter",
      "bilibili",
      "linkedin",
      "reddit",
      "weibo",
    ],
    listIsCeiling: true,
    enumerating: [],
    quiet: ["score_draft", "repurpose_post", "write_hooks", "create_variants", "draft_post"],
  },

  /**
   * Linking an account the workspace owns, which is a different question from
   * whether a network can be read. Gated at runtime on whether the deployment
   * holds OAuth credentials, so no static list is the truth and
   * list_social_connections is the live answer.
   */
  accountLink: {
    source: "nooticr_domain::Platform, gated by nooticr_publish::oauth_config",
    platforms: ["tiktok", "instagram", "youtube", "twitter"],
    listIsCeiling: true,
    beyondList: "availability is per-deployment; list_social_connections is the live answer",
    enumerating: [],
    quiet: ["connect_social_account", "list_social_connections"],
  },
} as const;

/** The platforms a capability serves — from the server where it publishes one. */
export function platformsFor(name: string): readonly string[] {
  return SERVED[name]?.platforms ?? CAPABILITIES[name]?.platforms ?? [];
}

/** Whether its list is a limit, or only the fast path. */
export function listIsCeiling(name: string): boolean {
  return SERVED[name]?.listIsCeiling ?? CAPABILITIES[name]?.listIsCeiling ?? true;
}

/** Platforms it reaches but cannot read comments on. */
export function commentsUnavailable(name: string): readonly string[] {
  return SERVED[name]?.commentsUnavailable ?? [];
}

/** Every platform name the checks know about. */
export const KNOWN_PLATFORMS: readonly string[] = [
  ...new Set([
    ...Object.values(SERVED).flatMap((c) => c.platforms),
    ...Object.values(CAPABILITIES).flatMap((c) => c.platforms ?? []),
  ]),
];

/** Which capability a tool belongs to, or undefined when it declares none. */
export function capabilityOf(tool: string): [string, Capability] | undefined {
  for (const [name, cap] of Object.entries(CAPABILITIES)) {
    if (cap.enumerating.includes(tool) || (cap.quiet ?? []).includes(tool)) {
      return [name, cap];
    }
  }
  return undefined;
}
